# Generated by Django 4.2.15 on 2024-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('parsed_result', models.TextField(blank=True, null=True)),
                ('vulnerabilities', models.JSONField(default=dict)),
            ],
        ),
    ]
